### ISSUE TITLE
Wrong agruments order in mar_logistic.py

### ISSUE THREAD

**Issue by shaodaqian** [WenjieDu/PyGrinder#42]
### 1. System Info

PyGrinder __version__ = "0.6.2"

### 2. Information

- [ ] The official example scripts
- [ ] My own created scripts

### 3. Reproduction

line 15: def _mar_logistic_torch(
    X: Union[np.ndarray, torch.Tensor],
    rate_obs: float,
    rate_missing: float)

line 125: corrupted_X = _mar_logistic_torch(X, missing_rate, obs_rate)

The order of argument passing is wrong.

### 4. Expected behavior

Use keyword arguments.

**Comment by WenjieDu** [comment]
Hi there 👋,

Thank you so much for your attention to PyGrinder and PyPOTS! You can follow me on GitHub to receive the latest news of PyGrinder and PyPOTS. If you find PyGrinder helpful to your work, please star⭐️ this repository. Your star is your recognition, which can help more people notice PyPOTS and grow PyPOTS community. It matters and is definitely a kind of contribution to the community.

I have received your message and will respond ASAP. Thank you for your patience! 😃

Best,
Wenjie
