### ISSUE TITLE
Bug of seq_missing

### ISSUE THREAD

**Issue by Chengyui** [WenjieDu/PyGrinder#45]
### Issue description

When seq_len set to as the length of time steps, the function seq_missing failed.
For example, feed the ts_dataset in the shape of (128,10,36) into seq_missing(ts_dataset, p=0.1, seq_len=10) it will failed.
The whole variable missing is also common in reality.

**Comment by WenjieDu** [comment]
Hi there 👋,

Thank you so much for your attention to PyGrinder and PyPOTS! You can follow me on GitHub to receive the latest news of PyGrinder and PyPOTS. If you find PyGrinder helpful to your work, please star⭐️ this repository. Your star is your recognition, which can help more people notice PyPOTS and grow PyPOTS community. It matters and is definitely a kind of contribution to the community.

I have received your message and will respond ASAP. Thank you for your patience! 😃

Best,
Wenjie

**Comment by WenjieDu** [comment]
Hi @Chengyui, try installing from the dev branch to fix this. Please let me know if it works.
